[2023-12-22T23:13:17.684+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_layer.batch_0 manual__2023-12-22T23:13:14.164588+00:00 [queued]>
[2023-12-22T23:13:17.689+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_layer.batch_0 manual__2023-12-22T23:13:14.164588+00:00 [queued]>
[2023-12-22T23:13:17.689+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-22T23:13:17.701+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): batch_0> on 2023-12-22 23:13:14.164588+00:00
[2023-12-22T23:13:17.705+0000] {standard_task_runner.py:60} INFO - Started process 1250 to run task
[2023-12-22T23:13:17.708+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'batch_layer', 'batch_0', 'manual__2023-12-22T23:13:14.164588+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayerDag.py', '--cfg-path', '/tmp/tmp3bfcqk7f']
[2023-12-22T23:13:17.711+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask batch_0
[2023-12-22T23:13:17.750+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_layer.batch_0 manual__2023-12-22T23:13:14.164588+00:00 [running]> on host f9bc372cbc19
[2023-12-22T23:13:17.807+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='batch_layer' AIRFLOW_CTX_TASK_ID='batch_0' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T23:13:14.164588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T23:13:14.164588+00:00'
[2023-12-22T23:13:17.859+0000] {hive.py:475} INFO - USE `finnhub_db`
[2023-12-22T23:13:17.891+0000] {hive.py:475} INFO - 
                SELECT *
                FROM finnhub_table
            
[2023-12-22T23:13:18.946+0000] {logging_mixin.py:188} INFO -           date  hour           s         sum_v
0   2023-12-17    21     BINANCE      92.05398
1   2023-12-20    19        AAPL  551388.00000
2   2023-12-20    19        AMZN  732498.00000
3   2023-12-20    19  IC MARKETS       0.00000
4   2023-12-21    21        AAPL      98.00000
5   2023-12-21    21        AMZN       7.00000
6   2023-12-21    21     BINANCE     172.97669
7   2023-12-22    15        AAPL    1360.00000
8   2023-12-22    15        AMZN     495.00000
9   2023-12-22    15     BINANCE       0.02745
10  2023-12-22    15        MSFT     615.00000
11  2023-12-22    20        AAPL   21145.00000
12  2023-12-22    20        AMZN   20715.00000
13  2023-12-22    20     BINANCE       4.28485
14  2023-12-22    20        MSFT   12085.00000
15  2023-12-22    21        AAPL    8446.00000
16  2023-12-22    21        AMZN     134.00000
17  2023-12-22    21     BINANCE     303.76186
[2023-12-22T23:13:18.947+0000] {logging_mixin.py:188} INFO - File '/tmp/batchViews/parquet_output.parquet' already exists.
[2023-12-22T23:13:18.957+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/BatchLayerDag.py", line 21, in batch_0
    b0.batch_proc_0()
  File "/opt/airflow/dags/batch_proc_0.py", line 67, in batch_proc_0
    df = pq.read_pandas('/tmp/batchViews/df.parquet').to_pandas()
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 3033, in read_pandas
    return read_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2926, in read_table
    dataset = _ParquetDatasetV2(
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/parquet/core.py", line 2466, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 1004, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '/tmp/batchViews/df.parquet': Parquet file size is 0 bytes
[2023-12-22T23:13:18.967+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=batch_layer, task_id=batch_0, execution_date=20231222T231314, start_date=20231222T231317, end_date=20231222T231318
[2023-12-22T23:13:18.976+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task batch_0 (Could not open Parquet input source '/tmp/batchViews/df.parquet': Parquet file size is 0 bytes; 1250)
[2023-12-22T23:13:19.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-22T23:13:19.014+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
