[2023-12-26T16:56:09.970+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: batch_layer.batch_0 manual__2023-12-26T16:47:30.882707+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
