[2023-12-22T15:56:34.802+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_layer.income_statement manual__2023-12-22T15:56:31.725215+00:00 [queued]>
[2023-12-22T15:56:34.868+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_layer.income_statement manual__2023-12-22T15:56:31.725215+00:00 [queued]>
[2023-12-22T15:56:34.869+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-22T15:56:34.880+0000] {taskinstance.py:2192} INFO - Executing <Task(SparkSubmitOperator): income_statement> on 2023-12-22 15:56:31.725215+00:00
[2023-12-22T15:56:34.883+0000] {standard_task_runner.py:60} INFO - Started process 325 to run task
[2023-12-22T15:56:34.885+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'batch_layer', 'income_statement', 'manual__2023-12-22T15:56:31.725215+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayerDag.py', '--cfg-path', '/tmp/tmpt2givhh6']
[2023-12-22T15:56:34.887+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask income_statement
[2023-12-22T15:56:34.915+0000] {task_command.py:423} INFO - Running <TaskInstance: batch_layer.income_statement manual__2023-12-22T15:56:31.725215+00:00 [running]> on host f1915694ab6b
[2023-12-22T15:56:34.952+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='batch_layer' AIRFLOW_CTX_TASK_ID='income_statement' AIRFLOW_CTX_EXECUTION_DATE='2023-12-22T15:56:31.725215+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-22T15:56:31.725215+00:00'
[2023-12-22T15:56:34.957+0000] {spark_submit.py:223} INFO - Could not load connection string spark-conn, defaulting to yarn
[2023-12-22T15:56:34.958+0000] {spark_submit.py:351} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark ./batch_proc_0.py
[2023-12-22T15:56:35.877+0000] {spark_submit.py:521} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-12-22T15:56:35.877+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2023-12-22T15:56:35.878+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2023-12-22T15:56:35.878+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2023-12-22T15:56:35.878+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2023-12-22T15:56:35.879+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2023-12-22T15:56:35.879+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2023-12-22T15:56:35.879+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2023-12-22T15:56:35.879+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2023-12-22T15:56:35.879+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2023-12-22T15:56:35.880+0000] {spark_submit.py:521} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-12-22T15:56:35.897+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 160, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 452, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark ./batch_proc_0.py. Error code is: 1.
[2023-12-22T15:56:35.900+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=batch_layer, task_id=income_statement, execution_date=20231222T155631, start_date=20231222T155634, end_date=20231222T155635
[2023-12-22T15:56:35.908+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 4 for task income_statement (Cannot execute: spark-submit --master yarn --name arrow-spark ./batch_proc_0.py. Error code is: 1.; 325)
[2023-12-22T15:56:35.942+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-22T15:56:35.950+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
