[2023-12-24T15:37:07.767+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:37:07.772+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:37:07.773+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T15:37:07.785+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T15:37:07.789+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T15:37:07.791+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmp4tip_jj8']
[2023-12-24T15:37:07.793+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T15:37:07.820+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host b2aeaa9190f5
[2023-12-24T15:37:07.975+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T15:37:15.981+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T15:37:15.982+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T15:37:18.320+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T153707, end_date=20231224T153718
[2023-12-24T15:37:18.330+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T15:37:18.357+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T15:37:18.366+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T15:41:59.229+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:41:59.246+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:41:59.247+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T15:41:59.283+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T15:41:59.299+0000] {standard_task_runner.py:60} INFO - Started process 188 to run task
[2023-12-24T15:41:59.304+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpqrhvyevs']
[2023-12-24T15:41:59.308+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T15:41:59.356+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 83b53490fe78
[2023-12-24T15:41:59.642+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T15:42:07.649+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T15:42:07.651+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T15:42:07.661+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T154159, end_date=20231224T154207
[2023-12-24T15:42:07.701+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 188)
[2023-12-24T15:42:07.743+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T15:42:07.756+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T15:51:29.540+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:51:29.545+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:51:29.545+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T15:51:29.556+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T15:51:29.560+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T15:51:29.562+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpgnzxczz1']
[2023-12-24T15:51:29.564+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T15:51:29.594+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host be1f0ffa1f05
[2023-12-24T15:51:29.744+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T15:51:37.748+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T15:51:37.749+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T15:51:37.755+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T155129, end_date=20231224T155137
[2023-12-24T15:51:37.764+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T15:51:37.771+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T15:51:37.780+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T17:03:14.931+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:03:14.936+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:03:14.937+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T17:03:14.949+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T17:03:14.956+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T17:03:14.966+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpy6wt90jz']
[2023-12-24T17:03:14.972+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T17:03:15.033+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 1e3b18e1227a
[2023-12-24T17:03:15.339+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T17:03:23.345+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T17:03:23.346+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T17:03:23.370+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T170314, end_date=20231224T170323
[2023-12-24T17:03:23.379+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T17:03:23.424+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T17:03:23.434+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T17:48:20.640+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:48:20.645+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:48:20.645+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T17:48:20.656+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T17:48:20.660+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T17:48:20.662+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpknyi8gia']
[2023-12-24T17:48:20.664+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T17:48:20.692+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 16ee60c2f1f1
[2023-12-24T17:48:20.822+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T17:48:28.828+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T17:48:28.829+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T17:48:28.834+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T174820, end_date=20231224T174828
[2023-12-24T17:48:28.845+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T17:48:28.880+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T17:48:28.888+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T18:11:25.281+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T18:11:25.286+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T18:11:25.287+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T18:11:25.297+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T18:11:25.302+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T18:11:25.305+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmphu6o9d21']
[2023-12-24T18:11:25.307+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T18:11:25.334+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host c0475b589502
[2023-12-24T18:11:25.474+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T18:11:33.480+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T18:11:33.481+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T18:11:33.493+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T181125, end_date=20231224T181133
[2023-12-24T18:11:33.501+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T18:11:33.536+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T18:11:33.545+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T19:01:14.612+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:01:14.617+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:01:14.618+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T19:01:14.634+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T19:01:14.638+0000] {standard_task_runner.py:60} INFO - Started process 187 to run task
[2023-12-24T19:01:14.641+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmptf49y0m6']
[2023-12-24T19:01:14.643+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T19:01:14.672+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host fffebfb72bbc
[2023-12-24T19:01:14.817+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T19:01:22.822+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T19:01:22.823+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T19:01:22.828+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T190114, end_date=20231224T190122
[2023-12-24T19:01:22.859+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 187)
[2023-12-24T19:01:22.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T19:01:22.883+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T19:06:14.401+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:06:14.408+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:06:14.408+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2023-12-24T19:06:14.421+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T19:06:14.427+0000] {standard_task_runner.py:60} INFO - Started process 191 to run task
[2023-12-24T19:06:14.430+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpsi33_6c1']
[2023-12-24T19:06:14.433+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask serving
[2023-12-24T19:06:14.464+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 465cb068660d
[2023-12-24T19:06:14.619+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T19:06:22.633+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T19:06:22.634+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T19:06:22.643+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T190614, end_date=20231224T190622
[2023-12-24T19:06:22.675+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task serving (local variable 'cursor' referenced before assignment; 191)
[2023-12-24T19:06:22.705+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T19:06:22.715+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
