[2023-12-24T15:56:41.743+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:56:41.747+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T15:56:41.747+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-24T15:56:41.757+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T15:56:41.761+0000] {standard_task_runner.py:60} INFO - Started process 351 to run task
[2023-12-24T15:56:41.763+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmposfc7y4y']
[2023-12-24T15:56:41.765+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask serving
[2023-12-24T15:56:41.791+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host be1f0ffa1f05
[2023-12-24T15:56:41.912+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T15:56:49.917+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T15:56:49.918+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T15:56:49.925+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T155641, end_date=20231224T155649
[2023-12-24T15:56:49.933+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task serving (local variable 'cursor' referenced before assignment; 351)
[2023-12-24T15:56:49.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T15:56:49.987+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T17:08:27.144+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:08:27.153+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T17:08:27.153+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-24T17:08:27.169+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T17:08:27.174+0000] {standard_task_runner.py:60} INFO - Started process 351 to run task
[2023-12-24T17:08:27.177+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpffbsph4a']
[2023-12-24T17:08:27.180+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask serving
[2023-12-24T17:08:27.210+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 1e3b18e1227a
[2023-12-24T17:08:27.345+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T17:08:35.351+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T17:08:35.352+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T17:08:35.358+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T170827, end_date=20231224T170835
[2023-12-24T17:08:35.366+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task serving (local variable 'cursor' referenced before assignment; 351)
[2023-12-24T17:08:35.406+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T17:08:35.414+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T18:16:35.759+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T18:16:35.764+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T18:16:35.764+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-24T18:16:35.774+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T18:16:35.778+0000] {standard_task_runner.py:60} INFO - Started process 341 to run task
[2023-12-24T18:16:35.781+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmpgscyavs3']
[2023-12-24T18:16:35.783+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask serving
[2023-12-24T18:16:35.811+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host c0475b589502
[2023-12-24T18:16:35.942+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T18:16:43.946+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T18:16:43.947+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T18:16:43.953+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T181635, end_date=20231224T181643
[2023-12-24T18:16:43.962+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task serving (local variable 'cursor' referenced before assignment; 341)
[2023-12-24T18:16:43.973+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T18:16:43.981+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-24T19:11:24.701+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:11:24.706+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [queued]>
[2023-12-24T19:11:24.706+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2023-12-24T19:11:24.717+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): serving> on 2023-12-23 00:00:00+00:00
[2023-12-24T19:11:24.720+0000] {standard_task_runner.py:60} INFO - Started process 341 to run task
[2023-12-24T19:11:24.722+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'serving-layer', 'serving', 'scheduled__2023-12-23T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/servingLayer.py', '--cfg-path', '/tmp/tmp6p4fsyhs']
[2023-12-24T19:11:24.724+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask serving
[2023-12-24T19:11:24.750+0000] {task_command.py:423} INFO - Running <TaskInstance: serving-layer.serving scheduled__2023-12-23T00:00:00+00:00 [running]> on host 465cb068660d
[2023-12-24T19:11:24.864+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='serving-layer' AIRFLOW_CTX_TASK_ID='serving' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-23T00:00:00+00:00'
[2023-12-24T19:11:32.868+0000] {logging_mixin.py:188} INFO - Error: could not translate host name "postgres" to address: Temporary failure in name resolution
[2023-12-24T19:11:32.869+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/servingLayer.py", line 79, in process_parquet_files
    if cursor:
UnboundLocalError: local variable 'cursor' referenced before assignment
[2023-12-24T19:11:32.875+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=serving-layer, task_id=serving, execution_date=20231223T000000, start_date=20231224T191124, end_date=20231224T191132
[2023-12-24T19:11:32.888+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task serving (local variable 'cursor' referenced before assignment; 341)
[2023-12-24T19:11:32.913+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-24T19:11:32.920+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
